# SwiftLint Configuration for Swift Finance App
disabled_rules:
  - trailing_whitespace
  - force_cast
  - force_try
  - todo
  # Temporarily disabled during cleanup - re-enable gradually
  - function_body_length
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - line_length

opt_in_rules:
  - empty_count
  - file_header
  - first_where
  - modifier_order
  - redundant_nil_coalescing
  - sorted_first_last
  - vertical_parameter_alignment_on_call

included:
  - FinanceApp/Sources
  - FinanceApp

excluded:
  - Pods
  - FinanceApp.xcodeproj
  - FinanceApp.xcworkspace
  - Carthage
  - .build
  - .git

# Rule configurations
line_length:
  warning: 120
  error: 150

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 400

cyclomatic_complexity:
  warning: 10
  error: 15

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50

reporter: "xcode" 